name: Merge me!

on:
  workflow_run:
    types:
      - completed
    workflows:
      - 'Check'

jobs:
  merge-me:
    name: Merge me!

    runs-on: ubuntu-latest

    steps:
      - name: Merge me!
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        uses: ridedott/merge-me-action@v2.9.60
        with:
          GITHUB_TOKEN: ${{ secrets.DEPENDABOT }}
          PRESET: DEPENDABOT_MINOR
