name: Auto-merge Dependabot PRs

on:
  workflow_run:
    types:
      - completed
    workflows:
      - "Check"

jobs:
  merge-me:
    name: Auto-merge Dependabot PRs
    runs-on: ubuntu-latest
    steps:
      - name: Auto-Merge
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        uses: ridedott/merge-me-action@v2.9.69
        with:
          GITHUB_TOKEN: ${{ secrets.DEPENDABOT }}
          MERGE_METHOD: MERGE
